// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 08.10.2026 14:15:05
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/Projects/hotel-frontend-nuxt/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Projects/hotel-frontend-nuxt/app/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Projects/hotel-frontend-nuxt/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Projects/hotel-frontend-nuxt/app/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Projects/hotel-frontend-nuxt/app/plugins/**/*.{js,ts,mjs}","C:/Projects/hotel-frontend-nuxt/app/composables/**/*.{js,ts,mjs}","C:/Projects/hotel-frontend-nuxt/app/utils/**/*.{js,ts,mjs}","C:/Projects/hotel-frontend-nuxt/app/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Projects/hotel-frontend-nuxt/app/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Projects/hotel-frontend-nuxt/app/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","C:/Projects/hotel-frontend-nuxt/app/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;